create database sonpdo;
use sonpdo;
create table alunos (id int not null primary key auto_increment, nome varchar(50) not null, nota int not null);
insert into alunos (nome, nota) values ('Juquinha',3);
insert into alunos (nome, nota) values ('Joaozinho',8);
insert into alunos (nome, nota) values ('Zezinho',6);
insert into alunos (nome, nota) values ('Fulaninho',2);
insert into alunos (nome, nota) values ('Ledesma',7);
insert into alunos (nome, nota) values ('Ramom',9);
insert into alunos (nome, nota) values ('Dante',10);
insert into alunos (nome, nota) values ('Joaninha',4);
insert into alunos (nome, nota) values ('Mariazinha',2);
insert into alunos (nome, nota) values ('Pedrinho',6);
insert into alunos (nome, nota) values ('Marquinhos',2);
insert into alunos (nome, nota) values ('Rosinha',7);
insert into alunos (nome, nota) values ('Dudu',8);
insert into alunos (nome, nota) values ('Edu',7);
insert into alunos (nome, nota) values ('Kadu',6);
insert into alunos (nome, nota) values ('Dani',3);
insert into alunos (nome, nota) values ('Beltraninho',1);
insert into alunos (nome, nota) values ('Gago',5);
insert into alunos (nome, nota) values ('Terezinha',7);
insert into alunos (nome, nota) values ('Gordo',9);

